# Nombre del workflow
name: CI - Test & Build Housing Prices

# Disparadores: Cuándo se debe ejecutar este workflow
on:
  # Se ejecuta en cada push a las ramas main o development
  push:
    branches: [ main, development ]
  # También se ejecuta cuando se abre o actualiza un Pull Request
  pull_request:

# Trabajos: 
jobs:
  test-and-build:
    # Máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Pasos
    steps:
      # Descarga tu código del repositorio a la máquina virtual
      - name: Checkout código
        uses: actions/checkout@v4

      # Configura el entorno de Python en la versión 3.11
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Instala las dependencias del proyecto
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e . # Instalación normal del paquete local

      # Ejecuta las pruebas unitarias con pytest
      - name: Ejecutar pruebas unitarias
        run: pytest -v

      # Construye la imagen de Docker para verificar que el Dockerfile funciona
      - name: Build imagen Docker (runtime)
        run: docker build --target runtime -t housing-api:test .